server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: challetapigateway-service
  cloud:
    gateway:
      routes:
        - id: challet-service
          uri: lb://CHALLET-SERVICE
          predicates:
            - Path=/challet-service/**

        - id: bank-service
          uri: lb://BANK-SERVICE
          predicates:
            - Path=/bank-service/**

        - id: kbbank-service
          uri: lb://KBBANK-SERVICE
          predicates:
            - Path=/kb-bank-service/**

        - id: nhbank-service
          uri: lb://NHBANK-SERVICE
          predicates:
            - Path=/nh-bank-service/**

        - id: shbank-service
          uri: lb://SHBANK-SERVICE
          predicates:
            - Path=/sh-bank-service/**


springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: ChalletService
      url: challet-service/v3/api-docs
    urls[1]:
      name: BankService
      url: bank-service/v3/api-docs
    urls[2]:
      name: KbBankService
      url: kb-bank-service/v3/api-docs
    urls[3]:
      name: NhBankService
      url: nh-bank-service/v3/api-docs
    urls[4]:
      name: ShBankService
      url: sh-bank-service/v3/api-docs