server:
  port: 8085

spring:
  config:
    import: application-key.yml
  application:
    name: shbank-service
  datasource:
    url: jdbc:mysql://challet.world:${dbport}/shbank-api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: challet
    password: ${mysqlpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: sh-bank-service/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json